name: C# CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results# This workflow uses actions that are not certified by GitHub.
